config/routes.rb
Unhcrkmja::Application.routes.draw do

  resources :news

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  match "home" =>  "pages#home"

  match "about_us" =>  "pages#about_us"

  match "programmes" => "pages#programmes"

  match "reports" => "pages#reports"

  resources :cases

  resources :judges do
    member do
      get 'cases'
      get 'trainings'
    end
  end

  resources :trainings do
    resources :training_sessions
    member do
      get 'participants'
      get 'publish'
      get 'retract'
    end
  end
  resources :causes

  root :to => 'pages#home'

end

app/models/training.rb
class Training < ActiveRecord::Base
  attr_accessible :name, :date, :remarks, :report, :publish
  has_many :training_sessions, dependent: :destroy
  has_many :judges, :through => :training_sessions
  has_attached_file :report

  validates :name, :date, :remarks, :report, presence: :true
  scope :publish?, where(:publish => true)

  def create_training_sessions(start_date, end_date, judges_tokens, location)
    training = self
    judges= Judge.find(judges_tokens.split(","))
    judges.each do |judge|
      training.training_sessions.create!(:judge_id => judge.id, :start_date => start_date, :end_date => end_date, :location => location)
    end
  end

  def publish
    training = self
    training.update_column(:publish, true)
  end

  def retract
    training = self
    training.update_column(:publish, false)
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_filter :authenticate_user!, :except => ["index", "show"]
  load_and_authorize_resource :except => [:index, :show]
  # GET /trainings
  # GET /trainings.json
  def publish
    @training = Training.find(params[:id])
    @training.publish
    respond_to do |format|
      format.html { redirect_to @training, notice: 'Training was successfully published.' }
    end
  end

  def retract
    @training = Training.find(params[:id])
    @training.retract
    respond_to do |format|
      format.html { redirect_to @training, notice: 'Training was successfully retracted.' }
    end
  end

  def participants
    @training = Training.find(params[:id])
    if params[:q].blank?
      @start_date = params[:start_date]
      @end_date = params[:end_date]
      @location = params[:location]
    else
      @start_date = params[:q][:start_date]
      @end_date = params[:q][:end_date]
      @location = params[:q][:location]
      params[:q].except!(:end_date, :start_date, :location)
    end
    @search = @training.training_sessions.search(params[:q])
    @training_sessions = @search.result.where(:start_date => @start_date, :end_date => @end_date, :location => @location)
    @judges = @training_sessions.map{|x| x.judge}
    if request.xhr?
        render :partial => 'participants', :object => @judges, :content_type => 'text/html'
      else
        respond_to do |format|
        format.html
        format.json { render json: @judges }
      end
      end
  end

  def index
    if user_signed_in?
      @search = Training.search(params[:q])
      @trainings = @search.result.paginate(:page => params[:page], :per_page => 10).order("id DESC")
    else
      @search = Training.search(params[:q])
      @trainings = @search.result.paginate(:page => params[:page], :per_page => 10).order("id DESC").publish?
    end
    if request.xhr?
        render :partial => 'trainings', :object => @trainings, :content_type => 'text/html'
      else
        respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @trainings }
      end
      end
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @training = Training.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @training }
    end
  end

  # GET /trainings/new
  # GET /trainings/new.json
  def new
    @training = Training.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @training }
    end
  end
  #FIXME training report on editing
  # GET /trainings/1/edit
  def edit
    @training = Training.find(params[:id])
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(params[:training])

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render json: @training, status: :created, location: @training }
      else
        format.html { render action: "new" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trainings/1
  # PUT /trainings/1.json

  def update
    @training = Training.find(params[:id])

    respond_to do |format|
      if @training.update_attributes(params[:training])
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training = Training.find(params[:id])
    @training.destroy

    respond_to do |format|
      format.html { redirect_to trainings_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%set_meta_tags :nofollow => true%>
<%= form_for(@training) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% @training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name%></br>
    <%= f.text_field :name, required: true%>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br />
    <%= f.cktext_area :remarks%>
  </div>
   <div class="field">
    <%= f.label :upload_report%></br>
    <%= f.file_field :report%>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/trainings/_participantSearch.html.erb
<ul class="nav nav-list">
        <li><h4>Search</h4></li>
</ul>
<%= search_form_for [@search] , :url => {:action =>  :participants }, remote: true, html: {class: "form-horizontal search_form", id: "participants_search"} do |f|%>
 <%= f.number_field :judge_membership_id_eq, placeholder: "Membership ID"%>
 <%= f.select :judge_designation_eq, Judge::DESIGNATIONS, include_blank: "#{'-'*10}Designation#{'-'*14}"%>
 <%= f.text_field :judge_name_cont, placeholder: "Name"%>
 <%= f.hidden_field :location, :value => @location%>
 <%= f.hidden_field :date, :value => @date%>
  <div class="action search_buttons">
 <%= f.submit "Search",class: "btn btn-primary btn-block"%>
  <%= link_to "clear", participants_training_path(@training, :date => @date, :location => @location) , class: "btn btn-warning btn-block"%>
 </div>
<%end%>

app/views/trainings/_participants.html.erb
<ul class="breadcrumb">
        <li><%= link_to "#{@training.name} held at: #{@location + " Date: " +@start_date}", training_training_sessions_path(@training)%> <span class="divider">/</span></li>
    <li class="active">Participants</li>
</ul>
<%if @judges.empty?%>
<span class="label label-warning">sorry no judges found</span>
<%else%>
<span class="label label-success"><%= pluralize(@judges.count, 'Judge') %> found</span>
<%end%>
<table class="table table-striped table-bordered table-hover table-condensed">
  <tr>
    <th>Membership ID</th>
    <th>Name</th>
    <th>Deisgnation</th>
  </tr>
  <% @judges.each do | judge|%>
  <tr>
  <td><%= judge.membership_id%></th>
  <td><%= judge.designation%></th>
  <td><%= judge.name%></td>
  <td><%= link_to "view member", judge, class: "btn btn-primary btn-small"%></td>
  </tr>
  <%end%>
 </table>

app/views/trainings/_search.html.erb
<ul class="nav nav-list">
        <li><h4>Search</h4></li>
</ul>
<%= search_form_for @search, remote: true, html: {class: "form-horizontal search_form", id: "training_search"} do |f| %>
  <div class="field">
  <%= f.text_field :name_cont, placeholder: "Training name"%>
  </div>
   <div class="field">
  <%= f.text_field :date_eq, class: "datepicker", placeholder: "Date"%>
  </div>
  <div class="field">
  <%= f.text_field :remarks_cont, placeholder: "Search phrase"%>
  </div>

  <div class="action search_buttons">
  <%= f.submit class: "btn btn-primary btn-block"%>

  <%= link_to "clear", trainings_path, class: "btn btn-warning btn-block"%>
  </div>

<%end%>

app/views/trainings/_trainings.html.erb
<%if @trainings.empty?%>
<span class="label label-warning">sorry no reports found</span>
<%else%>
<span class="label label-success"><%= pluralize(@trainings.count, 'report') %> found</span>
<%end%>
<% @trainings.each do |training| %>
  <article class="report">
    <h4><%= training.name%></h4>
    <p class="pull-right"><span>Date: </span><%= training.date %></p>
    <p><%= training.remarks.html_safe %></p>
    <p>
  <%= image_tag "pdf.png"%>
  <%= link_to "download report", training.report.url%>
  </p>
  <p class="pull-right">
  <% if can? :edit, training%>
    <%= link_to 'Show', training, class: "btn btn-mini btn-info"%>
    <%= link_to "Edit", edit_training_path(training), class: "btn btn-mini btn-warning"%>
    <%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %>
    <% if training.publish?%>
      <%= link_to "Retract", retract_training_path(training), class: "btn btn-mini btn-danger"%>
    <%else%>
    <%= link_to "Publish", publish_training_path(training), class: "btn-mini btn-primary btn"%>

    <%end%>
    <%end%>
  </p>
  </article>
<% end %>
<br />
<%= will_paginate @trainings, class: "pagination"%>

app/views/trainings/edit.html.erb
<%set_meta_tags :nofollow => true%>
<h1>Editing training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training, class: "btn" %> |
<%= link_to 'Back', trainings_path(@judge), class: "btn" %>

app/views/trainings/index.html.erb
<%set_meta_tags :title => 'Training Reports', :reverse => true%>
<div class="row-fluid wrapper">
<div class="span3" id="search">
  <%= render "search"%>
</div>
<div class="span9" id="reports">
<%= render "trainings"%>
</div>
</div>

app/views/trainings/new.html.erb
<%set_meta_tags :nofollow => true%>
<h1>New training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path, class: "btn" %>

app/views/trainings/participants.html.erb
<div class="row-fluid wrapper">
<div class="span3" id="search">
         <%= render partial: "participantSearch", locals: {:date => @date, :location => @location}%>
</div>
<div class="span9" id="participants">
<%= render "participants"%>
</div>
</div>

app/views/trainings/show.html.erb
<p>
  <b>Name:</b>
  <%= @training.name%>
</p>
<p>
  <b>Date:</b>
  <%= @training.date %>
</p>

<p>
  <b>Remarks:</b>
  <%= @training.remarks.html_safe %>
</p>
<p>
  <%= image_tag "pdf.png"%>
  <%= link_to "download full report", @training.report.url%>
</p>


<%= link_to 'Edit', edit_training_path(@training), class: "btn" %> |
<%= link_to 'Back', trainings_path, class: "btn" %>
<% if @training.publish?%>
      <%= link_to "Retract", retract_training_path(@training), class: "btn btn-danger"%>
    <%else%>
    <%= link_to "Publish", publish_training_path(@training), class: "btn btn-primary"%>

    <%end%>
<%= link_to 'add a training session', new_training_training_session_path(@training), class: "btn btn-primary"%>
<%= link_to 'view training sessions', training_training_sessions_path(@training), class: "btn btn-primary"%>