config/routes.rb
Unhcrkmja::Application.routes.draw do

  resources :news

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  match "home" =>  "pages#home"

  match "about_us" =>  "pages#about_us"

  match "programmes" => "pages#programmes"

  match "reports" => "pages#reports"

  resources :cases

  resources :judges do
    member do
      get 'cases'
      get 'trainings'
    end
  end

  resources :trainings do
    resources :training_sessions
    member do
      get 'participants'
      get 'publish'
      get 'retract'
    end
  end
  resources :causes

  root :to => 'pages#home'

end

app/models/judge.rb
class Judge < ActiveRecord::Base
  attr_accessible :name, :membership_id, :designation
  has_many :training_sessions, dependent: :destroy
  has_many  :cases, inverse_of: :judge, dependent: :destroy
  has_many :trainings, :through => :training_sessions

  validates :membership_id, :designation, :name, presence: true
  validates :membership_id, :numericality => { :only_integer => true }, :uniqueness => true


  JUDGES = Judge.all.map{|judge| [judge.name, judge.id]}
  DESIGNATIONS = ["JUSTICE", "HON"]

end

app/controllers/judges_controller.rb
class JudgesController < ApplicationController
  before_filter :authenticate_user!
  def cases
    @judge = Judge.find(params[:id])
    @search = @judge.cases.search(params[:q])
    @cases = @search.result.paginate(:page => params[:page], :per_page => 20).order("id ASC")
    if request.xhr?
        render :partial => 'casespartial', :object => @cases, :content_type => 'text/html'
      else
        respond_to do |format|
        format.html
        format.json { render json: @cases }
      end
    end
  end

  def trainings
    @judge = Judge.find(params[:id])
    @search = @judge.training_sessions.search(params[:q])
    @training_sessions = @search.result.paginate(:page => params[:page], :per_page => 20).order("id ASC")
    if request.xhr?
        render :partial => 'trainingspartial', :object => @training_sessions, :content_type => 'text/html'
      else
        respond_to do |format|
        format.html
        format.json { render json: @cases }
      end
    end
  end

  # GET /judges
  # GET /judges.json
  def index
    if request.xhr?
      @judges = Judge.where("name like ?", "%#{params[:q]}%")
    else
      @search = Judge.search(params[:q])
      @judges = @search.result.paginate(:page => params[:page], :per_page => 20).order("id ASC")

    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @judges }
    end
  end

  # GET /judges/1
  # GET /judges/1.json
  def show
    @judge = Judge.find(params[:id])
    @training_sessions = @judge.training_sessions
    @cases = @judge.cases

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @judge }
    end
  end

  # GET /judges/new
  # GET /judges/new.json
  def new
    @judge = Judge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @judge }
    end
  end

  # GET /judges/1/edit
  def edit
    @judge = Judge.find(params[:id])
  end

  # POST /judges
  # POST /judges.json
  def create
    @judge = Judge.new(params[:judge])

    respond_to do |format|
      if @judge.save
        format.html { redirect_to @judge, notice: 'Judge was successfully created.' }
        format.json { render json: @judge, status: :created, location: @judge }
      else
        format.html { render action: "new" }
        format.json { render json: @judge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /judges/1
  # PUT /judges/1.json
  def update
    @judge = Judge.find(params[:id])

    respond_to do |format|
      if @judge.update_attributes(params[:judge])
        format.html { redirect_to @judge, notice: 'Judge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @judge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /judges/1
  # DELETE /judges/1.json
  def destroy
    @judge = Judge.find(params[:id])
    @judge.destroy

    respond_to do |format|
      format.html { redirect_to judges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/judges_helper.rb
module JudgesHelper
end

app/views/judges/_casesSearch.html.erb
<%set_meta_tags :nofollow => true%>
<ul class="nav nav-list">
        <li><h4>Search</h4></li>
</ul>
<%= search_form_for @search, remote: true, url: {action: :cases}, html: {class: "form-horizontal search_form", id: "judges_cases"} do |f| %>
  <div class="field">
  <%causes = Cause.all.map{|cause| [cause.name+" - "+cause.category, cause.id]}%>
    <%= f.select :cause_id_eq, options_for_select(causes), include_blank: "select Cause"%>

  </div>
 <div class="field">
  <%= f.text_field :case_number_cont, placeholder: "Case number"%>
  </div>
  <div class="field">
    <%= f.select :court_cont, Cause::COURTS, include_blank: "select Court"%>
  </div>
   <div class="field">
  <%= f.text_field :year_of_judgement_eq, class: "datepicker", placeholder: "Date"%>
  </div>
  <div class="field">
  <%= f.text_field :complainant_cont, placeholder: "Complainant"%>
  </div>
  <div class="field">
  <%= f.text_field :defendant_cont, placeholder: "Defendant"%>
  </div>
  <div class="field">
  <%= f.text_field :accused_cont, placeholder: "Accused"%>
  </div>
  <div class="action search_buttons">
  <%= f.submit class: "btn btn-primary btn-block"%>

  <%= link_to "clear", cases_judge_path(@judge), class: "btn btn-warning btn-block"%>
  </div>

<%end%>

app/views/judges/_casespartial.html.erb
<ul class="breadcrumb">
         <li><%= link_to "#{@judge.designation + " "+@judge.name}".upcase!, @judge%> <span class="divider">/</span></li>
    <li class="active">Cases</li>
 </ul>
<%if @cases.empty?%>
<span class="label label-warning">sorry no cases found</span>
<%else%>
<span class="label label-success"><%= pluralize(@cases.count, 'case') %> found</span>
<%end%>
<table class="table table-striped table-bordered table-hover table-condensed">
  <tr>
    <th><%= sort_link @search, :case_number, "Case number"%></th>
    <th>Parties</th>
    <th><%= sort_link @search, :cause, "Cause"%></th>
    <th><%= sort_link @search, :category, "Category"%></th>
    <th><%= sort_link @search, :year_of_judgement, "Date"%></th>
    <th><%= sort_link @search, :court, "Court"%></th>
  </tr>
  <% @cases.each do |cases| %>
  <tr>
    <td><%= cases.case_number %></td>
    <td> <% if cases.cause.category == "criminal"%>
     <%= cases.state %> vs. <%= cases.accused %>
    <%else%>
     <%= cases.complainant %> vs. <%= cases.defendant %>
    <%end%></td>
    <td><%= cases.cause.name%></td>
    <td><%= cases.cause.category%></td>
    <td><%= cases.year_of_judgement %></td>
    <td><%= cases.court%></td>
    <td><%= link_to "show", cases, class: "btn btn-primary btn-mini"%></td>
  </tr>
  <%end%>
  </table>
<%= will_paginate @cases%>

app/views/judges/_form.html.erb
<%set_meta_tags :nofollow => true%>
<%= form_for(@judge) do |f| %>
  <% if @judge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@judge.errors.count, "error") %> prohibited this judge from being saved:</h2>

      <ul>
      <% @judge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, required: true%>
  </div>
  <div class="field">
    <%= f.label :membership_id, "Membership ID"%><br />
    <%= f.number_field :membership_id, required: true%>
 </div>
   <div class="field">
     <%= f.label :designation%>
     <%= f.select :designation, Judge::DESIGNATIONS, include_blank: "Designation", required: true%>
   </div>


  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/judges/_judges.html.erb
<%set_meta_tags :nofollow => true%>
<ul class="breadcrumb">
   <li class="active">Judges</li>
   </ul>
<%if @judges.empty?%>
<span class="label label-warning">sorry no judges found</span>
<%else%>
<span class="label label-success"><%= pluralize(@judges.count, 'Judge') %> found</span>
<%end%>
<br />
<table class="table table-striped table-bordered table-hover table-condensed">
  <tr>
   <th><%= sort_link @search, :membership_id, "Membership ID"%></th>
    <th><%= sort_link @search, :designation, "Designation"%>
    <th><%= sort_link @search, :name, "Name"%></th>
    <th></th>
    <th>
  </tr>

<% @judges.each do |judge| %>
  <tr>
    <td><%= judge.membership_id%></td>
    <td><%= judge.designation%></td>
    <td class="judge"><%= judge.name %></td>

    <td><%= link_to 'Show', judge, class: "btn btn-mini btn-info" %></td>
    <td><%= link_to 'Edit', edit_judge_path(judge), class: "btn btn-mini btn-warning" %></td>
    <td><%= link_to 'Destroy', judge, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @judges, class: "pagination"%>

app/views/judges/_search.html.erb
<ul class="nav nav-list">
        <li><h4>Search</h4></li>
</ul>
<%= search_form_for @search,  html: {class: "form-horizontal search_form"} do |f|%>
<div class="field">
 <%= f.number_field :membership_id_eq, placeholder: "Membership ID"%>
</div>
<div class="field">
 <%= f.select :designation_eq, Judge::DESIGNATIONS, include_blank: "#{'-'*10}Designation#{'-'*14}"%>
</div>
<div class="field">
 <%= f.text_field :name_cont, placeholder: "Name"%>
</div>
<div class="action search_buttons">
 <%= f.submit "Search", class: "btn btn-primary btn-block"%>
  <%= link_to "clear", judges_path, class: "btn btn-warning btn-block"%>
 </div>
<%end%>

app/views/judges/_trainingsSearch.html.erb
<%set_meta_tags :nofollow => true%>
<ul class="nav nav-list">
        <li><h4>Search</h4></li>
</ul>
<%= search_form_for @search, remote: :true, url: {action: :trainings}, html: {class: "form-horizontal search_form", id: "judges_trainings"} do |f| %>
  <div class="field">
  <%= f.text_field :training_name_cont, placeholder: "Training name"%>
  </div>
  <div class="field">
  <%= f.text_field :location_cont, placeholder: "Training location"%>
  </div>
   <div class="field">
  <%= f.text_field :date_eq, class: "datepicker", placeholder: "Date"%>
  </div>
   <div class="field">
  <%= f.text_field :training_remarks_cont, placeholder: "Search phrase"%>
  </div>

  <div class="action search_buttons">
  <%= f.submit class: "btn btn-primary btn-block"%>

  <%= link_to "clear", trainings_judge_path(@judge), class: "btn btn-warning btn-block"%>
  </div>

<%end%>

app/views/judges/_trainingspartial.html.erb
<ul class="breadcrumb">
         <li><%= link_to "#{@judge.designation + " "+@judge.name}".upcase!, @judge%> <span class="divider">/</span></li>
    <li class="active">Trainings</li>
</ul>
<%if @training_sessions.empty?%>
<span class="label label-warning">sorry no cases found</span>
<%else%>
<span class="label label-success"><%= pluralize(@training_sessions.count, 'training') %> found</span>
<%end%>
<table class="table table-striped table-bordered table-hover table-condensed">
  <tr>
  <th>Training</th>
  <th>Date of training</th>
  <th>Location</th>
  </tr>
  <%@training_sessions.each do |training_session|%>
   <tr>
     <td><%= training_session.training.name%></td>
     <td><%= training_session.date%></td>
     <td><%= training_session.location%></td>
     <td><%= link_to "training", training_session.training, class: "btn btn-primary btn-mini"%></td>
   </tr>
  <%end%>
</table>
<%= will_paginate @training_sessions%>

app/views/judges/cases.html.erb
<div class="row-fluid wrapper">
<div class="span3" id="search">
<%= render "casesSearch"%>
</div>
<div class="span9" id="cases_for_judges">
  <%= render "casespartial"%>
</div>
</div>

app/views/judges/edit.html.erb
<%set_meta_tags :nofollow => true%>
<h1>Editing judge</h1>

<%= render 'form' %>

<%= link_to 'Show', @judge, class: "btn" %> |
<%= link_to 'Back', judges_path, class: "btn" %>

app/views/judges/index.html.erb
<%set_meta_tags :nofollow => true%>

<div class="row-fluid wrapper">
<div class="span3" id="search">
  <%= render "search"%>
</div>
<div class="span9" id="judges">
<%= render "judges"%>
</div>
</div>

app/views/judges/new.html.erb
<%set_meta_tags :nofollow => true%>
<h1>New judge</h1>

<%= render 'form' %>

<%= link_to 'Back', judges_path, class: "btn" %>

app/views/judges/show.html.erb
<%set_meta_tags :nofollow => true%>
<ul class="breadcrumb">
         <li><%= link_to "Judges".upcase!, judges_path%> <span class="divider">/</span></li>
    <li class="active"><%= "#{@judge.designation + " " +@judge.name.upcase}"%></li>
 </ul>

<p>
  <b><%= @judge.designation%></b>
  <%= @judge.name %>
</p>
<p>
 <b>Membership_id:</b>
 <%= @judge.membership_id%>
</p>


<br />
<br />
<%= link_to 'Edit', edit_judge_path(@judge), class: "btn" %> |
<%= link_to 'Back', judges_path, class: "btn" %>
<%= link_to "View cases", cases_judge_path, class: "btn btn-primary"%>
<%= link_to "View trainings", trainings_judge_path, class: "btn btn-primary"%>

app/views/judges/trainings.html.erb
<%set_meta_tags :nofollow => true%>
<div class="row-fluid wrapper">
<div class="span3" id="search">
<%= render "trainingsSearch"%>
</div>
<div class="span9" id="trainings_for_judges">
  <%= render "trainingspartial"%>
</div>
</div>