config/routes.rb
Unhcrkmja::Application.routes.draw do

  resources :news

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  match "home" =>  "pages#home"

  match "about_us" =>  "pages#about_us"

  match "programmes" => "pages#programmes"

  match "reports" => "pages#reports"

  resources :cases

  resources :judges do
    member do
      get 'cases'
      get 'trainings'
    end
  end

  resources :trainings do
    resources :training_sessions
    member do
      get 'participants'
      get 'publish'
      get 'retract'
    end
  end
  resources :causes

  root :to => 'pages#home'

end

app/models/training_session.rb
class TrainingSession < ActiveRecord::Base
  belongs_to :judge
  belongs_to :training
  attr_accessible :judge_id, :training_id, :end_date, :start_date, :judge_tokens, :location
  has_attached_file :original_list
  validates :end_date , :start_date, :location, presence: true

  attr_reader :judge_tokens
  def judge_tokens=(ids)
    ids.split(",")
  end


end

app/controllers/training_sessions_controller.rb
class TrainingSessionsController < ApplicationController
  before_filter :authenticate_user!, :except => ["index", "show"]
  load_and_authorize_resource :except => [:index, :show]
  # GET /training_sessions
  # GET /training_sessions.json
  def index
    @training = Training.find(params[:training_id])
    #@training_sessions = @training.training_sessions.group("date", "location").select(["location", "date"])
    @search = @training.training_sessions.search(params[:q])
    @training_sessions = @search.result.paginate(:page => params[:page], :per_page => 20).group("start_date", "end_date", "location").select(["start_date", "location", "end_date"])

    if request.xhr?
        render :partial => 'training_sessions', :object => @training_sessions, :content_type => 'text/html'
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @training_sessions }
      end
    end
  end

  # GET /training_sessions/1
  # GET /training_sessions/1.json
  def show
    @training_session = TrainingSession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @training_session }
    end
  end

  # GET /training_sessions/new
  # GET /training_sessions/new.json
  def new
    @training = Training.find(params[:training_id])
    @training_session = TrainingSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @training_session }
    end
  end

  # GET /training_sessions/1/edit
  def edit
    @training_session = TrainingSession.find(params[:id])
  end

  # POST /training_sessions
  # POST /training_sessions.json
  def create
    @training = Training.find(params[:training_id])
    @training.create_training_sessions(params[:training_session][:start_date], params[:training_session][:end_date], params[:training_session][:judge_tokens], params[:training_session][:location])
    @training_session = TrainingSession.new(params[:training_session].except(:judge, :training))

    respond_to do |format|
      if @training_session.valid?

        format.html { redirect_to @training, notice: 'Training session was successfully created.' }
        format.json { render json: @training, status: :created, location: @training_session }
      else
        format.html { render action: "new" }
        format.json { render json: @training_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /training_sessions/1
  # PUT /training_sessions/1.json
  def update
    @training_session = TrainingSession.find(params[:id])

    respond_to do |format|
      if @training_session.update_attributes(params[:training_session])
        format.html { redirect_to @training_session, notice: 'Training session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_sessions/1
  # DELETE /training_sessions/1.json
  def destroy
    @training_session = TrainingSession.find(params[:id])
    @training_session.destroy

    respond_to do |format|
      format.html { redirect_to training_sessions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/training_sessions_helper.rb
module TrainingSessionsHelper
end

app/views/training_sessions/_form.html.erb
<%set_meta_tags :nofollow => true%>
<%= form_for([@training, @training_session]) do |f| %>
  <% if @training_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training_session.errors.count, "error") %> prohibited this training_session from being saved:</h2>

      <ul>
      <% @training_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date, class: "datepicker", required: true%>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date, class: "datepicker", required: true%>
  </div>
  <div class="field">
     <%= f.label :location%><br/>
     <%= f.text_field :location, required: true%>
  </div>
  <div class="field">
    <%= f.label :judge_tokens, "Judges" %><br />
    <%= f.text_field :judge_tokens, id: "judges_tokens", required: true%>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/training_sessions/_search.html.erb
<%set_meta_tags :nofollow => true%>
<ul class="nav nav-list">
        <li><h4>Search</h4></li>
</ul>
<%= search_form_for [@training, @search], remote: true, html: {class: "form-horizontal search_form", id: "training_session_search"} do |f| %>
  <div class="field">
  <%= f.text_field :location_cont, placeholder: "Training location"%>
  </div>
   <div class="field">
  <%= f.text_field :start_date_eq, class: "datepicker", placeholder: "Date"%>
  </div>
  <div class="field">
  <%= f.text_field :end_date_eq, class: "datepicker", placeholder: "Date"%>
  </div>

  <div class="action search_buttons">
  <%= f.submit class: "btn btn-primary btn-block"%>

  <%= link_to "clear", training_training_sessions_path(@training), class: "btn btn-warning btn-block"%>
  </div>

<%end%>

app/views/training_sessions/_training_sessions.html.erb
<%set_meta_tags :nofollow => true%>
<ul class="breadcrumb">
        <li><%= link_to @training.name, @training%> <span class="divider">/</span></li>
    <li class="active">Training sessions</li>
   </ul>
<table class="table table-striped table-bordered table-hover table-condensed">
  <tr>
    <th><%= sort_link @search, :start_date, "Start of training"%></th>
     <th><%= sort_link @search, :end_date, "End of training"%></th>
   <th><%= sort_link @search, :location, "Location of training"%></th>
    <th></th>

  </tr>

<% @training_sessions.each do |training_session| %>
  <tr>
       <td><%= training_session.start_date %></td>
      <td><%= training_session.end_date %></td>
       <td><%= training_session.location%></td>
       <td><%= link_to "view participants", participants_training_path(@training, :start_date => training_session.start_date, :end_date =>  training_session.end_date, :location => training_session.location) , class: "btn btn-primary btn-small"%></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @training_sessions, class: "pagination"%>

app/views/training_sessions/edit.html.erb
<%set_meta_tags :nofollow => true%>
<h1>Editing training_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @training_session %> |
<%= link_to 'Back', training_sessions_path %>

app/views/training_sessions/index.html.erb
<%set_meta_tags :nofollow => true%>
<div class="row-fluid wrapper">
<div class="span3" id="search">
  <%= render "search"%>
</div>
<div class="span9" id="training_sessions">
<%= render "training_sessions"%>
</div>
</div>

app/views/training_sessions/new.html.erb
<h1>New training_session</h1>

<%= render 'form' %>

app/views/training_sessions/show.html.erb
<%set_meta_tags :nofollow => true%>
<p id="notice"><%= notice %></p>

<p>
  <b>Judge:</b>
  <%= @training_session.judge.name %>
</p>

<p>
  <b>Traning:</b>
  <%= @training_session.training.name %>
</p>

<p>
  <b>Start Date:</b>
  <%= @training_session.start_date %>
</p>
<p>
  <b>End Date:</b>
  <%= @training_session.end_date %>
</p>


<%= link_to 'Edit', edit_training_training_session_path([@training, @training_session]) %> |
<%= link_to 'Back', training_training_sessions_path(@training) %>