config/routes.rb
Unhcrkmja::Application.routes.draw do

  resources :news

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  match "home" =>  "pages#home"

  match "about_us" =>  "pages#about_us"

  match "programmes" => "pages#programmes"

  match "reports" => "pages#reports"

  resources :cases

  resources :judges do
    member do
      get 'cases'
      get 'trainings'
    end
  end

  resources :trainings do
    resources :training_sessions
    member do
      get 'participants'
      get 'publish'
      get 'retract'
    end
  end
  resources :causes

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="row-fluid">
		<div class="span8">
			<p class="offset4">
	Copyright © 2013 The Kenya Magistrates and Judges Association. All Rights Reserved
	</p>
	</div>
	<div class="span4">
	<%= link_to "Contact Us", contact_us_path%>
	</div>
</div>
</footer>

app/views/layouts/_logos.html.erb
<div class="row-fluid" id ="logos">
    <div class="span2 hidden-phone">
      <a href="http://www.kmja.or.ke" target="_blank" title="The kenya magistrates and judges association" class="offset3"><%= image_tag "kmja_log.png"%></a>
    </div>
    <div class="span8 title">
      <h2 class ="hidden-phone">COURT DECISIONS ON REFUGEE MATTERS</h2>
       <h4 class ="visible-phone">COURT DECISIONS ON REFUGEE MATTERS</h4>
      <p>
        <h5>No human being is illegal</h5>
      </p>
    </div>
    <div class="hidden-phone span2">
      <a href="http://www.unhcr.org" target="_blank" title="UNHCR"><%= image_tag "unhcr_logo.png"%></a>
    </div>
  </div>

app/views/layouts/_main_nav.html.erb
<%= render "layouts/logos"%>
<div class="navbar" id="main_nav">
   <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="nav-collapse collapse">
            <ul class="nav">
    <li><%= link_to "Home", home_path%></li>
    <li><%= link_to "About us", about_us_path%></li>
    <li><%= link_to "The Programme", programmes_path%></li>
    <li><%= link_to "Judgments", cases_path%></li>
    <li><%= link_to "Reports", trainings_path%></li>
  </ul>
</div>
</div>
</div>
</div>

app/views/layouts/_nav.html.erb
<div class="navbar">
  <%= render "layouts/logos"%>
  <div class="navbar-inner" id="admin_nav">
    <ul class="nav">
      <li>
        <%= link_to "Home", home_path%>
      </li>
      <li>
        <%= link_to "About Us", about_us_path%>
      </li>
      <li>
        <%= link_to "The Programme", programmes_path%>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Judges <b class="caret"></b> </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "View Judges", judges_path%>
          </li>
          <li>
            <%= link_to "Add a Judge", new_judge_path%>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Trainings <b class="caret"></b> </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "View Trainings", trainings_path%>
          </li>
          <li>
            <%= link_to "Add a Trainig", new_training_path%>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Causes <b class="caret"></b> </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "View Causes", causes_path%>
          </li>
          <li>
            <%= link_to "Add a Cause", new_cause_path%>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Cases <b class="caret"></b> </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "View Cases", cases_path%>
          </li>
          <li>
            <%= link_to "Add a Case", new_case_path%>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> News <b class="caret"></b> </a>
        <ul class="dropdown-menu">
         <li>
           <%= link_to "View News", news_index_path%>
         </li>
         <li>
          <%= link_to "Add news", new_news_path%>
         </li>
        </ul>
      </li>
       <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
         <%= current_user.email%><b class="caret"></b>
         </a>
         <ul class="dropdown-menu">
           <li><%= link_to "Change your password", edit_user_registration_path %></li>
           <li><%= link_to "logout", destroy_user_session_path, method: :delete%></li>
          </ul>
      </li>
      </nav>
  </div>
</div>

app/views/layouts/_nav.mobile.erb
<div data-role="navbar">
	<ul>
		<li>
			<%= link_to "home", home_url, html: {rel: "external"}%>
		</li>
		<li>
			<%= link_to "About Us ", about_us_url%>
		</li>
		<li>
			<%= link_to "Programmes", programmes_url%>
		</li>
		<li>
			<%= link_to "Cases", cases_url%>
		</li>
		<li>
			<%= link_to "Reports", trainings_url%>
	    </li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= display_meta_tags :site => 'Court decisions on refugee matters' %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/nav'%>
    <% else%>
    <%= render 'layouts/main_nav'%>
    <%end%>
    <div  class="container-fluid" id="main-content">
      <% if notice.present?%>
      <span class="label label-success"><%= notice %></span>
      <%end%>
      <% if alert.present?%>
      <span class="label label-warning offset3"><%= alert %></span>
      <%end%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Decisions</title>
    <%= stylesheet_link_tag "http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.css"%>
    <%= javascript_include_tag 'http://code.jquery.com/jquery-1.8.3.min.js',"http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.js" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= yield%>
  </body>
</html>